#============================================
# Global variables for Prometheus Playbook
#============================================
# Node Exporter configuration
node_exporter_version: "1.8.1"
node_exporter_user: "node_exporter"
node_exporter_port: 9100
node_exporter_install_dir: "/usr/local/bin"
node_exporter_systemd_dir: "/etc/systemd/system"

# Prometheus configuration
prometheus_version: "2.52.0"
prometheus_user: "prometheus"
prometheus_port: 9090
prometheus_install_dir: "/usr/local/bin"
prometheus_config_dir: "/etc/prometheus"
prometheus_data_dir: "/var/lib/prometheus"
prometheus_systemd_dir: "/etc/systemd/system"

#scrape interval for prometheus
prometheus_scrape_interval: "15s"
prometheus_evaluation_interval: "15s"

#Retention time for prometheus data
prometheus_retention_time: "15d"
